#!/usr/bin/env bash
# Write .env.lean by pulling Secrets Manager values (never prints secret bodies).
#
# Prerequisites: AWS_PROFILE with secretsmanager:GetSecretValue on oziebot/* 
#
# DATABASE_URL defaults to local Docker Postgres (recommended with ECS/RDS still
# running—you avoid split-brain on RDS/ElastiCache). Paste RDS URL manually only after
# scale-to-zero AND network path to RDS (same VPC/SG or SSH tunnel)—see README_LEAN_MODE.md.
#
# Usage:
#   export AWS_PROFILE=oziebot
#   ./infrastructure/lean/bootstrap-lean-env-from-aws.sh
#
# Optional:
#   LEAN_DATABASE_TARGET=rds    # omit POSTGRES_* and sets DATABASE_URL from AWS secret as-is

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "${ROOT}"

REGION="${AWS_REGION:-us-east-1}"

get_secret_plain() {
  aws secretsmanager get-secret-value \
    --region "${REGION}" \
    --secret-id "$1" \
    --query SecretString \
    --output text 2>/dev/null || echo ""
}

OUT="${ROOT}/.env.lean"

if [[ -f "${OUT}" && "${LEAN_BOOTSTRAP_OVERWRITE:-0}" != "1" ]]; then
  echo "${OUT} already exists; set LEAN_BOOTSTRAP_OVERWRITE=1 to replace." >&2
  exit 1
fi

jwt="$(get_secret_plain oziebot/prod/api/jwt-secret)"
enc="$(get_secret_plain oziebot/prod/shared/exchange-credentials-encryption-key)"
stripe_key="$(get_secret_plain oziebot/prod/api/stripe-secret-key)"
stripe_hook="$(get_secret_plain oziebot/prod/api/stripe-webhook-secret)"
sms="$(get_secret_plain oziebot/prod/alerts/sms-webhook-url)"
slack="$(get_secret_plain oziebot/prod/alerts/slack-webhook-url)"
telegram="$(get_secret_plain oziebot/prod/alerts/telegram-bot-token)"

if [[ "${LEAN_DATABASE_TARGET:-local}" == "rds" ]]; then
  db="$(get_secret_plain oziebot/prod/shared/database-url)"
  pg_user=""
  pg_pass=""
else
  db=""
  pg_user="oziebot"
  pg_pass="$(openssl rand -hex 16)"
fi

umask 077
{
  cat << EOF
# Generated by bootstrap-lean-env-from-aws.sh — DO NOT COMMIT
# Regenerate: LEAN_BOOTSTRAP_OVERWRITE=1 $0

REDIS_URL=redis://redis:6379/0
LEAN_API_BIND=${LEAN_API_BIND:-127.0.0.1}
APP_ENV=production
CORS_ORIGINS=https://app.oziebot.com
RUN_DB_MIGRATIONS_ON_STARTUP=1
COINBASE_API_BASE_URL=https://api.coinbase.com

EOF

  if [[ "${LEAN_DATABASE_TARGET:-local}" == "rds" ]]; then
    echo "DATABASE_URL=${db}"
  else
    echo "POSTGRES_USER=${pg_user}"
    echo "POSTGRES_PASSWORD=${pg_pass}"
    echo "POSTGRES_DB=oziebot"
    echo "DATABASE_URL=postgresql+psycopg://${pg_user}:${pg_pass}@postgres:5432/oziebot"
  fi

  cat << EOF

JWT_SECRET=${jwt}
EXCHANGE_CREDENTIALS_ENCRYPTION_KEY=${enc}

STRIPE_SECRET_KEY=${stripe_key}
STRIPE_WEBHOOK_SECRET=${stripe_hook}
STRIPE_CHECKOUT_SUCCESS_URL=https://app.oziebot.com/billing/success?session_id={CHECKOUT_SESSION_ID}
STRIPE_CHECKOUT_CANCEL_URL=https://app.oziebot.com/billing/cancel

OZIEBOT_STRATEGY_DEMO=0
OZIEBOT_TRADING_MODE=paper
OZIEBOT_STRATEGY_RUNNER_POLL_SEC=1.0

RISK_STALE_TRADE_SECONDS=20
RISK_STALE_BBO_SECONDS=15
RISK_STALE_CANDLE_SECONDS=180

PAPER_DEFAULT_FEE_BPS=15
PAPER_DEFAULT_SLIPPAGE_BPS=8
RECONCILIATION_INTERVAL_SECONDS=60

NOTIFY_MAX_RETRIES=3
SMS_WEBHOOK_URL=${sms}
SLACK_WEBHOOK_URL=${slack}
TELEGRAM_BOT_TOKEN=${telegram}

COINBASE_WS_URL=wss://advanced-trade-ws.coinbase.com
COINBASE_REST_URL=https://api.coinbase.com/api/v3/brokerage
CANDLES_GRANULARITY_SEC=60
RAW_TRADE_LOG_ENABLED=false
OPS_ALERTS_ENABLED=false
SIGNAL_PANEL_ENABLED=true

API_SLOW_REQUEST_MS=2000
API_SLOW_QUERY_MS=500
EOF
} > "${OUT}"

echo "Wrote ${OUT} (mode 600)."
if [[ "${LEAN_DATABASE_TARGET:-local}" == "local" ]]; then
  echo "Local Postgres password is in DATABASE_URL / POSTGRES_PASSWORD (keep this file private)."
fi
echo "Next: docker compose -f docker-compose.lean.yml --env-file .env.lean up -d --build"
