from __future__ import annotations

ASSIGNMENT_TYPES = (
    "QUIZ",
    "WRITTEN_ASSIGNMENT",
    "EXIT_TICKET",
    "HOMEWORK",
    "PROJECT",
)

MVP_ASSIGNMENT_TYPES = ("QUIZ", "WRITTEN_ASSIGNMENT")

ASSIGNMENT_STATUSES = ("DRAFT", "GENERATED", "ACTIVE", "COMPLETED", "ARCHIVED")

ARTIFACT_TO_ASSIGNMENT_TYPE = {
    "quiz": "QUIZ",
    "assignment": "WRITTEN_ASSIGNMENT",
}

ASSIGNMENT_CREATING_ARTIFACT_TYPES = frozenset(ARTIFACT_TO_ASSIGNMENT_TYPE.keys())
