from __future__ import annotations

ASSIGNMENT_TYPES = (
    "QUIZ",
    "WRITTEN_ASSIGNMENT",
    "WRITING",
    "EXIT_TICKET",
    "HOMEWORK",
    "PROJECT",
    "GRADE_ENTRY",
)

MVP_ASSIGNMENT_TYPES = ("QUIZ", "WRITTEN_ASSIGNMENT", "WRITING")

ASSIGNMENT_STATUSES = ("DRAFT", "GENERATED", "ACTIVE", "COMPLETED", "ARCHIVED")

ASSIGNMENT_CREATION_ORIGINS = ("PACKAGE", "TEACHER_MANUAL", "TEACHER_GRADE_ENTRY")

PRINT_PACKET_KINDS = ("STUDENT_PACKET", "COVER_SHEET")

ARTIFACT_TO_ASSIGNMENT_TYPE = {
    "quiz": "QUIZ",
    "assignment": "WRITTEN_ASSIGNMENT",
    "writing_response": "WRITING",
}

ASSIGNMENT_CREATING_ARTIFACT_TYPES = frozenset(ARTIFACT_TO_ASSIGNMENT_TYPE.keys())
