from __future__ import annotations

INSTRUCTIONAL_PLAN_GENERATION_FEATURE = "weekly_plan_generation"
WEEKLY_PLAN_GENERATION_FEATURE = INSTRUCTIONAL_PLAN_GENERATION_FEATURE
INSTRUCTIONAL_PLAN_SECTION_REGENERATION_FEATURE = "weekly_plan_section_regeneration"
INSTRUCTIONAL_PLAN_PROMPT_VERSION = "instructional-plan-v2"
INSTRUCTIONAL_PLAN_SECTION_REGEN_PROMPT_VERSION = "instructional-plan-section-v1"
INSTRUCTIONAL_PLAN_ARTIFACT_SUGGESTIONS = ("daily_deck", "quiz", "guided_notes")
WEEKLY_PLAN_ARTIFACT_SUGGESTIONS = INSTRUCTIONAL_PLAN_ARTIFACT_SUGGESTIONS
INSTRUCTIONAL_PLAN_DAY_LABELS = {
    1: "Monday",
    2: "Tuesday",
    3: "Wednesday",
    4: "Thursday",
    5: "Friday",
}
WEEKLY_PLAN_DAY_LABELS = INSTRUCTIONAL_PLAN_DAY_LABELS
