from __future__ import annotations

INSTRUCTIONAL_PLAN_GENERATION_FEATURE = "weekly_plan_generation"
WEEKLY_PLAN_GENERATION_FEATURE = INSTRUCTIONAL_PLAN_GENERATION_FEATURE
INSTRUCTIONAL_PLAN_SECTION_REGENERATION_FEATURE = "weekly_plan_section_regeneration"
INSTRUCTIONAL_PLAN_PROMPT_VERSION = "instructional-plan-v2"
INSTRUCTIONAL_PLAN_SECTION_REGEN_PROMPT_VERSION = "instructional-plan-section-v1"
GRADING_ASSIST_FEATURE = "grading_assist"
GRADING_DRAFT_GENERATION_FEATURE = "grading_draft_generation"
GRADING_ASSIST_PROMPT_VERSION = "grading-assist-v1"
V2_INSTRUCTIONAL_PACKAGE_GENERATION_FEATURE = "instructional_package_generation"
V2_LESSON_PLAN_GENERATION_FEATURE = "lesson_plan_generation"
V2_SLIDE_GENERATION_FEATURE = "slide_generation"
V2_ASSIGNMENT_GENERATION_FEATURE = "assignment_generation"
V2_QUIZ_GENERATION_FEATURE = "quiz_generation"
V2_RUBRIC_GENERATION_FEATURE = "rubric_generation"
V2_NEWSLETTER_GENERATION_FEATURE = "newsletter_generation"
V2_EXIT_TICKET_GENERATION_FEATURE = "exit_ticket_generation"
V2_BELL_RINGER_GENERATION_FEATURE = "bell_ringer_generation"
V2_VOCABULARY_LIST_GENERATION_FEATURE = "vocabulary_list_generation"
V2_STUDY_GUIDE_GENERATION_FEATURE = "study_guide_generation"
V2_PACKAGE_ARTIFACT_FEATURES = {
    "daily_lesson_plan": V2_LESSON_PLAN_GENERATION_FEATURE,
    "subject_slide_deck": V2_SLIDE_GENERATION_FEATURE,
    "assignment": V2_ASSIGNMENT_GENERATION_FEATURE,
    "quiz": V2_QUIZ_GENERATION_FEATURE,
    "rubric": V2_RUBRIC_GENERATION_FEATURE,
    "exit_ticket": V2_EXIT_TICKET_GENERATION_FEATURE,
    "bell_ringer": V2_BELL_RINGER_GENERATION_FEATURE,
    "vocabulary_list": V2_VOCABULARY_LIST_GENERATION_FEATURE,
    "study_guide": V2_STUDY_GUIDE_GENERATION_FEATURE,
    "parent_newsletter_summary": V2_NEWSLETTER_GENERATION_FEATURE,
}
RETEACH_PLAN_AI_FEATURE = "reteach_plan_ai_draft"
RETEACH_PLAN_AI_PROMPT_VERSION = "reteach-plan-ai-v1"
NEWSLETTER_AI_FEATURE = "newsletter_generation"
NEWSLETTER_AI_PROMPT_VERSION = "newsletter-ai-v1"
NEWSLETTER_SECTION_REGEN_FEATURE = "newsletter_section_regeneration"
NEWSLETTER_SECTION_REGEN_PROMPT_VERSION = "newsletter-section-v1"
LESSON_REFLECTION_AI_FEATURE = "lesson_reflection_ai_suggestions"
LESSON_REFLECTION_AI_PROMPT_VERSION = "lesson-reflection-ai-v1"
INSTRUCTIONAL_PLAN_ARTIFACT_SUGGESTIONS = ("daily_deck", "quiz", "guided_notes")
WEEKLY_PLAN_ARTIFACT_SUGGESTIONS = INSTRUCTIONAL_PLAN_ARTIFACT_SUGGESTIONS
INSTRUCTIONAL_PLAN_DAY_LABELS = {
    1: "Monday",
    2: "Tuesday",
    3: "Wednesday",
    4: "Thursday",
    5: "Friday",
}
WEEKLY_PLAN_DAY_LABELS = INSTRUCTIONAL_PLAN_DAY_LABELS
