from __future__ import annotations

INSTRUCTIONAL_PLAN_GENERATION_FEATURE = "weekly_plan_generation"
WEEKLY_PLAN_GENERATION_FEATURE = INSTRUCTIONAL_PLAN_GENERATION_FEATURE
INSTRUCTIONAL_PLAN_SECTION_REGENERATION_FEATURE = "weekly_plan_section_regeneration"
INSTRUCTIONAL_PLAN_PROMPT_VERSION = "instructional-plan-v2"
INSTRUCTIONAL_PLAN_SECTION_REGEN_PROMPT_VERSION = "instructional-plan-section-v1"
GRADING_ASSIST_FEATURE = "grading_assist"
GRADING_ASSIST_PROMPT_VERSION = "grading-assist-v1"
RETEACH_PLAN_AI_FEATURE = "reteach_plan_ai_draft"
RETEACH_PLAN_AI_PROMPT_VERSION = "reteach-plan-ai-v1"
NEWSLETTER_AI_FEATURE = "newsletter_generation"
NEWSLETTER_AI_PROMPT_VERSION = "newsletter-ai-v1"
NEWSLETTER_SECTION_REGEN_FEATURE = "newsletter_section_regeneration"
NEWSLETTER_SECTION_REGEN_PROMPT_VERSION = "newsletter-section-v1"
INSTRUCTIONAL_PLAN_ARTIFACT_SUGGESTIONS = ("daily_deck", "quiz", "guided_notes")
WEEKLY_PLAN_ARTIFACT_SUGGESTIONS = INSTRUCTIONAL_PLAN_ARTIFACT_SUGGESTIONS
INSTRUCTIONAL_PLAN_DAY_LABELS = {
    1: "Monday",
    2: "Tuesday",
    3: "Wednesday",
    4: "Thursday",
    5: "Friday",
}
WEEKLY_PLAN_DAY_LABELS = INSTRUCTIONAL_PLAN_DAY_LABELS
